title: Paul Schneidewind Telge
logo: logo.jpg
description: Master Student at Ludwig-Maximilian-Universität<br> USM
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: 
  another_url: 
