title: Paul Schneidewind Telge
logo: logo.png
description: Minimal is a theme for GitHub Pages?
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: 
  another_url: 
